services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: go run ./cmd/server
        ports:
            - '8000:8000'
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db
        networks:
            - web
        env_file:
            - .env

    crawler:
        build:
            context: .
            dockerfile: Dockerfile
        command: go run ./cmd/crawler
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - db
        networks:
            - web
        env_file:
            - .env

    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./migrations/schema.sql:/docker-entrypoint-initdb.d/migrations/schema.sql
        networks:
            - web
        env_file:
            - .env

    precalculate:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "while :; do go run ./cmd/precalculate || echo 'Precalculation failed at $(date)'; sleep 3600; done"
        depends_on:
            - db
        env_file:
            - .env
        networks:
            - web

    reddit_frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - web

volumes:
    postgres_data:

networks:
    web:
        external: true
