services:

  db:
    env_file:
    - .env
    image: postgres:16
    container_name: reddit_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit_app
    networks:
      - web
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: