services:
  db:
    image: postgres:16
    container_name: reddit_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit_app
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web

volumes:
  pgdata:

networks:
  web:
    external: true