version: '3'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        command: go run ./cmd/server
        ports:
            - '8080:8080'
        environment:
            - DATABASE_URL=postgres://postgres:7onr1MC%2FO2DLEjIr7lqCNE125o6Wd5Phmh6z3mioipE%3D@db:5432/reddit_cluster?sslmode=disable
        depends_on:
            - db

    crawler:
        build:
            context: .
            dockerfile: Dockerfile
        command: go run ./cmd/crawler
        environment:
            - DATABASE_URL=postgres://postgres:7onr1MC%2FO2DLEjIr7lqCNE125o6Wd5Phmh6z3mioipE%3D@db:5432/reddit_cluster?sslmode=disable
        depends_on:
            - db

    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=7onr1MC/O2DLEjIr7lqCNE125o6Wd5Phmh6z3mioipE=
            - POSTGRES_DB=reddit_cluster
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

networks:
    web:
        external: true
