services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      web:
        aliases:
          - reddit-api
    env_file:
      - .env

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    depends_on:
      - db
    networks:
      - web
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount only the base schema to ensure correct init order
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    networks:
      - web
    env_file:
      - .env
    command: postgres -c fsync=on -c synchronous_commit=on -c full_page_writes=on -c wal_level=replica

  precalculate:
    build:
      context: .
      dockerfile: Dockerfile.precalculate
    command: >
      sh -c "
      while :; do
          # Run precalculation
          /app/precalculate || echo 'Precalculation failed at $(date)'
          
          # Run database backup
          /app/scripts/backup.sh || echo 'Backup failed at $(date)'
          
          # Sleep for an hour
          sleep 3600
      done"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - web
    volumes:
      - ./scripts:/app/scripts
      - ./backups:/app/backups

  reddit_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      web:
        aliases:
          - reddit_frontend
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  web:
    external: true
